services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - api-db:/app/services/api/prisma
    develop:
      watch:
        - action: rebuild
          path: services/api
    restart: always

  manager:
    build:
      context: services/manager
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: rebuild
          path: services/manager
    restart: always

  web:
    build:
      context: web
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://api:8000/api}
      NEXT_PUBLIC_MANAGER_BASE_URL: ${NEXT_PUBLIC_MANAGER_BASE_URL:-http://manager:8000/api}
    depends_on:
      - api
      - manager
    develop:
      watch:
        - action: sync
          path: web
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: web/package-lock.json
    restart: always

volumes:
  api-db:
