services:
  api:
    build:
      context: services/api
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: rebuild
          path: services/api
    restart: always

  manager:
    build:
      context: services/manager
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: rebuild
          path: services/manager
    restart: always

  web:
    build:
      context: web
      dockerfile: Dockerfile
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: web
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: web/package-lock.json
    restart: always
