services:
  api:
    extends:
      file: compose.yaml
      service: api
    depends_on:
      - postgres
      - traefik

  manager:
    extends:
      file: compose.yaml
      service: manager
    depends_on:
      - postgres
      - traefik

  web:
    extends:
      file: compose.yaml
      service: web
    depends_on:
      - api
      - traefik

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  traefik:
    image: traefik:v3.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

volumes:
  postgres-data:
