services:
  api:
    build:
      context: services/api
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: rebuild
          path: services/api
    restart: always

  manager:
    build:
      context: services/manager
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: rebuild
          path: services/manager
    restart: always

  web:
    build:
      context: web
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=PathPrefix(`/`)"
      - "traefik.http.routers.web.entrypoints=web,websecure"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: web
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: web/package-lock.json
    restart: always
