services:
  api:
    extends:
      file: compose.yaml
      service: api

  manager:
    extends:
      file: compose.yaml
      service: manager

  web:
    extends:
      file: compose.yaml
      service: web
