services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - RUNPOD_KEY=${RUNPOD_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    develop:
      watch:
        - action: rebuild
          path: api
    restart: always

  web:
    build:
      context: web
      dockerfile: Dockerfile
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: web
          target: /app
          ignore:
            - node_modules
        - action: rebuild
          path: web/package-lock.json
    restart: always
