[project]
name = "seed"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=2.19.1",
    "python-dotenv>=1.0.1",
    "openai>=1.14.3",
    "tqdm>=4.66.5",
    "weaviate-client>=4.0.0",
    "pydantic>=2.7.0",
]
